# Generated by Django 4.2.3 on 2023-07-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docker_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='command',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='app',
            name='image',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='run',
            name='parameters',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[('Running', 'Running'), ('Finished', 'Finished')], max_length=63),
        ),
    ]
