# Generated by Django 4.2.3 on 2023-07-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docker_app', '0002_alter_app_command_alter_app_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='storage_location',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
